const icons = {
  "clear-day": require("./clear-day.png"),
  "clear-night": require("./clear-night.png"),
  "cloudy": require("./cloudy.png"),
  "fog": require("./fog.png"),
  "hail": require("./hail.png"),
  "partly-cloudy-day": require("./partly-cloudy-day.png"),
  "partly-cloudy-night": require("./partly-cloudy-night.png"),
  "rain-snow-showers-day": require("./rain-snow-showers-day.png"),
  "rain-snow-showers-night": require("./rain-snow-showers-night.png"),
  "rain-snow": require("./rain-snow.png"),
  "rain": require("./rain.png"),
  "showers-day": require("./showers-day.png"),
  "showers-night": require("./showers-night.png"),
  "sleet": require("./sleet.png"),
  "snow-showers-day": require("./snow-showers-day.png"),
  "snow-showers-night": require("./snow-showers-night.png"),
  "snow": require("./snow.png"),
  "thunder-rain": require("./thunder-rain.png"),
  "thunder-showers-day": require("./thunder-showers-day.png"),
  "thunder-showers-night": require("./thunder-showers-night.png"),
  "thunder": require("./thunder.png"),
  "wind": require("./wind1.png"),
  "min-temp": require("./min-temp.png"),
  "max-temp": require("./max-temp.png"),
  "sunrise": require("./sunrise.png"),
  "sunset": require("./sunset.png"),
  "visibility": require("./visibility.png"),
  "humidity": require("./humidity.png"),
  "uv": require("./uv.png"),
};

export default icons;
